main:
	gcc -Wall -c task1_lib.c
	gcc -Wall -c task1_sys.c
	gcc -Wall task1_lib.o task1_sys.o main.c -o main

time:
	gcc -Wall -c task1_lib.c
	gcc -Wall -c task1_sys.c
	gcc -Wall task1_lib.o task1_sys.o time.c -o time
clean:
	rm -f *.o main time
