main:
	gcc -Wall -c task2_lib.c
	gcc -Wall -c task2_sys.c
	gcc -Wall task2_lib.o task2_sys.o main.c -o main

time:
	gcc -Wall -c task2_lib.c
	gcc -Wall -c task2_sys.c
	gcc -Wall task2_lib.o task2_sys.o time.c -o time
clean:
	rm -f *.o main time